Repository hanshulll/HACKTOBERFEST2021, pull requests merged in 2021-10, with the labels that each got.

#14 Added WordCloud Generator
  PYTHON/word_cloud_generator.py
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#16 Added String program
  C++/Print-all-subsequences-of-a-string.cpp
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#32 Unit Converter using python GUI (tkinter)
  PYTHON/Units_Converter.py
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#33 BMR Calculator
  PYTHON/BMR Calculator.py
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#35 Palindrome.java added
  JAVA/Palindrome.java
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#34 Design Pattern
  DesignPattern/Singleton/AppRunner.java
  DesignPattern/Singleton/Employee.java
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#30 Create break_a_palindrome.cpp
  C++/break_a_palindrome.cpp
  C++/valid_parentheses.cpp
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#29 Create VolumendSurfaceofcone
  C++/VolumendSurfaceofcone
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#28 Create electricityBill
  JAVA/electricityBill
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#40 Different expression of 3 variables Java
  JAVA/Expression.java
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#38 Data structure implementations using C
  C/BinarySearchIfElse.c
  C/BinarySearchRecursion.c
  C/DoublyLinkedList.c
  C/PolynomialCalculation.c
  C/Queue from stack.c
  C/SingleLinkedList.c
  C/Stacks.c
  C/readme.md
  C/sparsematrix.c
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#44 Matrix multiplication code
  .DS_Store
  C++/matrix-multiply.cpp
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#43 Create remove_duplicates.py
  PYTHON/remove_duplicates.py
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#47 Finding a sub-array which adds to a given number S
  C/FindSubContiguousArrayAddition.c
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#45 Create Fibanacci_numbers_by_replacing_prime_numbers_and_multiples_of_…
  PYTHON/Fibanacci_numbers_by_replacing_prime_numbers_and_multiples_of_5_by_0.py
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#50 checking palindrome front and from back at X distance
  JAVA/XPalindromesOfString.java
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#51 Create Splash screen.dart
  Dart/Splash screen.dart
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#53 Create Themes.dart
  Dart/Themes.dart
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#52 Create Tabs.dart
  Dart/Tabs.dart
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#55 Fight for hokage
  JAVA/FightForHokage.java
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#37 Currency converter in python
  PYTHON/Currency_Converter.py
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#39 added java method to generate hash code from any string
  JAVA/SHA256Encryption.java
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#54 added two C++ projects of Railway Reservation System and Library Management system
  C++/Library Management System/LBMS/Library Management System.cbp
  C++/Library Management System/LBMS/Library Management System.depend
  C++/Library Management System/LBMS/Library Management System.layout
  C++/Library Management System/LBMS/Library.CPP
  C++/Library Management System/LBMS/bin/Debug/Library Management System.exe
  C++/Library Management System/LBMS/bin/Debug/book.dat
  C++/Library Management System/LBMS/bin/Debug/student.dat
  C++/Library Management System/LBMS/book.dat
  C++/Library Management System/LBMS/obj/Debug/Library.o
  C++/Library Management System/LBMS/obj/Debug/main.o
  C++/Library Management System/LBMS/student.dat
  C++/Library Management System/Library Management System.exe
  C++/Library Management System/book.dat
  C++/Library Management System/student.dat
  C++/Railway Reservation System/Railway Reservation system.CPP
  C++/Railway Reservation System/Railway Reservation system.exe
  C++/Railway Reservation System/Railway Reservation system.o
  JAVA/OrderManagementSystem/.gitignore
  JAVA/OrderManagementSystem/.mvn/wrapper/MavenWrapperDownloader.java
  JAVA/OrderManagementSystem/.mvn/wrapper/maven-wrapper.jar
  JAVA/OrderManagementSystem/.mvn/wrapper/maven-wrapper.properties
  JAVA/OrderManagementSystem/mvnw
  JAVA/OrderManagementSystem/mvnw.cmd
  JAVA/OrderManagementSystem/pom.xml
  JAVA/OrderManagementSystem/src/main/java/com/example/ordermanagementsystem/OrderManagementSystemApplication.java
  JAVA/OrderManagementSystem/src/main/java/com/example/ordermanagementsystem/controller/OrderController.java
  JAVA/OrderManagementSystem/src/main/java/com/example/ordermanagementsystem/entity/Order.java
  JAVA/OrderManagementSystem/src/main/java/com/example/ordermanagementsystem/exception/OrderNotFoundException.java
  JAVA/OrderManagementSystem/src/main/java/com/example/ordermanagementsystem/repository/OrderRepository.java
  JAVA/OrderManagementSystem/src/main/java/com/example/ordermanagementsystem/service/IOrderService.java
  JAVA/OrderManagementSystem/src/main/java/com/example/ordermanagementsystem/service/OrderService.java
  JAVA/OrderManagementSystem/src/main/resources/application.properties
  JAVA/OrderManagementSystem/src/test/java/com/example/ordermanagementsystem/OrderManagementSystemApplicationTests.java
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#59 Added Reverse Array Operation
  JAVA/ReverseArray.class
  JAVA/ReverseArray.java
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#62 implemented stack array algorithm using Java language
  JAVA/StackArray.java
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#65 Program to get keyboard input using Go
  Go/keyboardInput.go
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#63 Added C++ code for Longest Increasing Path
  .gitignore
  C++/LongestIncreasingPath.cpp
  JAVA/.DS_Store
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#41 Create combination_sum.cpp
  C++/combination_sum.cpp
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#42 Kth largest element in Generic Trees
  JAVA/Kth largest element in Generic Trees.java
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#48 Create Sorted linked list to binary search tree.java
  JAVA/Remove duplicates in linkedlist
  JAVA/Sorted linked list to binary search tree.java
  PYTHON/Sum of two matrix.py
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#67 length of longest substring
  JAVA/lengthOfLongestSubstring.java
  JAVA/maxConsecutiveOnes.java
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#56 Create PasswordGen.py
  PYTHON/PasswordGen.py
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#57 Remove Duplicate Element From Array Code
  RemoveDuplicateFromArray.java
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#58 Added Kadane Algo in JAVA
  JAVA/Kadane.java
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#61 Create permutations.cpp
  C++/permutations.cpp
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#60 Added Façade design pattern
  DesignPattern/FacadePattern/.idea/.gitignore
  DesignPattern/FacadePattern/.idea/misc.xml
  DesignPattern/FacadePattern/.idea/modules.xml
  DesignPattern/FacadePattern/.idea/vcs.xml
  DesignPattern/FacadePattern/Circle.java
  DesignPattern/FacadePattern/Demo.java
  DesignPattern/FacadePattern/FacadeMaker.java
  DesignPattern/FacadePattern/FacadePattern.iml
  DesignPattern/FacadePattern/Rectangle.java
  DesignPattern/FacadePattern/Shape.java
  DesignPattern/FacadePattern/Triangle.java
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#64 Feat: C++: Trapping Rainwater Problem
  C++/trappingRainWater.cpp
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#66 Create Heap sort .c
  C/Heap sort .c
  PYTHON/tictactoe.py
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#70 Added some DP Problems
  C++/01Knapsack.cpp
  C++/LCS.cpp
  C++/MCM.cpp
  C++/allPossibleWays.cpp
  C++/coinChange.cpp
  C++/coinTower.cpp
  C++/editDistance.cpp
  C++/fibonacci.cpp
  C++/friendsPair.cpp
  C++/longestIncreasingSubsequence.cpp
  C++/lootHouses.cpp
  C++/maximizeCutSegments.cpp
  C++/minCostPath.cpp
  C++/minCountofSquares.cpp
  C++/minStepsTo1.cpp
  C++/nthCatalanNumber.cpp
  C++/numOfBalancedBT.cpp
  C++/permutationCoefficient.cpp
  C++/shortestSubsequence.cpp
  C++/squareMatrixWithZeroes.cpp
  C++/staircase.cpp
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#71 added add-remove program
  JavaScript/add-remove.html
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#77 Add Kadane's Algorithm
  C++/Kadane's Algorithm.cpp
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#75 Added CodeChef Problem Solved
  C++/CodeChef/Triangle With Angle/README.md
  C++/CodeChef/Triangle With Angle/Triangle With Angle.cpp
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#68 codechef problem in java
  JAVA/KthMaximum.java
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#78 Created check_binary_tree_subtree.cpp
  C++/check_binary_tree_subtree.cpp
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#80 Added Hashing (JAVA)
  .idea/.gitignore
  .idea/Hacktoberfest2021.iml
  .idea/compiler.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/runConfigurations.xml
  .idea/vcs.xml
  JAVA/Hashing/ModuloHashing.java
  JAVA/Hashing/PseudoRandHashing.java
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#83 added foobar level 2 solution in java
  JAVA/foobar_level_challenge.java
  JAVA/foobar_lucky_lambs.java
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#81 thirdmaximumelementinarray.java
  JAVA/thirdMaximumElementInArray
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#87 Created connect_n_ropes_min_cost_priority_queue.cpp
  C++/connect_n_ropes_min_cost_priority_queue.cpp
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#90 Branch2 shruti
  JAVA/foobar_re_is.java
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#86 FirstandLastElement
  JAVA/FindFirstandLastPositionofElementinSortedArray.java
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#89 Added a CodeChef Starters problem
  C++/Codechef/Diagonal Movement.md
  C++/Codechef/Diagonal movement code.cpp
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#85 Repeated String Match.cpp
  C++/Repeated String Match.cpp
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#99 Added insertion sort
  C++/Insertion sort.cpp
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#73 Adding fibonacci in javascript.
  JavaScript/fibonacci.js
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#72 Create FIND_FREQUENCY_OF_ELEMENTS_IN_A_GIVEN_ARRAY.java
  JAVA/FIND_FREQUENCY_OF_ELEMENTS_IN_A_GIVEN_ARRAY.java
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#100 An simple python program was added
  PYTHON/Sum_of_n_number_recursion.py
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#74 hamiltonian path and cycle
  C++/hamiltonianPathandCycle.cpp
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#76 Feat: Two Sum Problem: Leetcode 1
  C++/twoSum.cpp
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#106 added Radix sort
  C++/RadixSort.cpp
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#82 Added permuting two arrays(HackerRank problem)
  HackeRank/permuting_two_arrays.py
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#114 QR CODE generator in Python
  PYTHON/QR_CODE_GENERATOR/QrCodeGenerator.py
  PYTHON/QR_CODE_GENERATOR/bg_image1.png
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#111 Create Countdown Timer.py
  PYTHON/Countdown Timer.py
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#118 A Drink Water Reminder Using Python
  PYTHON/drink_water_notifier.py
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#120 Added GUI Calculator
  PYTHON/calculator(GUI).py
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#122 Selection sort in java
  JAVA/SelectionSort.java
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#126 E-Mail Sender in Python
  PYTHON/E-mail_Sender.py
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#125 Added Stack and Queue implementation in C#
  C#/Queue.cs
  C#/Stack.cs
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#124 HappyNumber.py
  HappyNumber.py
  PYTHON/HappyNumber.py
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#123 Create randomColorGen.js
  JavaScript/randomColorGen.js
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#129 Frequency of each element in the array
  C++/FrequencyEachElement.cpp
  C++/FrequencyEachElement.exe
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#131 Added a JS project (A simple two player dice game).
  JavaScript/PigDiceGame/app.js
  JavaScript/PigDiceGame/back.jpg
  JavaScript/PigDiceGame/dice-1.png
  JavaScript/PigDiceGame/dice-2.png
  JavaScript/PigDiceGame/dice-3.png
  JavaScript/PigDiceGame/dice-4.png
  JavaScript/PigDiceGame/dice-5.png
  JavaScript/PigDiceGame/dice-6.png
  JavaScript/PigDiceGame/index.html
  JavaScript/PigDiceGame/style.css
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#128 Flatten A Binary Tree
  C++/flattenABinaryTree.cpp
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#130 non duplicate array
  JAVA/NonDupArray.java
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#69 Create Ranking.java
  Ranking.java
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#84 Count total set bits.cpp
  C++/Count total set bits.cpp
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#93 added recursive power calculation file
  C++/logarathmic.cpp
  JavaScript/promisesample.js
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#98 Create matrixinzigzag.cpp
  C++/matrixinzigzag.cpp
  PYTHON/Paper-stone-scissors-game.py
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#104 Create disable-all.js
  JavaScript/disable-all.js
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#96 Added queue using array
  C/Queue using array.c
  C/QuickSort.c
  C/Selection sort.c
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#105 Median of 2 Sorted Arrays of Different Sizes.cpp
  C++/Median of 2 Sorted Arrays of Different Sizes.cpp
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#107 Create majority-element.cpp
  C++/majority-element.cpp
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#108 Added total unordered ways of coin change
  C++/totalunorderedwaysofcoinchange.cpp
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#110 Create primefactors.cpp
  C++/primefactors.cpp
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#112 Create left-view-of-binary-tree.cpp
  C++/left-view-of-binary-tree.cpp
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#115 Hackerrank problem Sorted Subsegments
  HackeRank/SortedSubsegments.py
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#116 min changes| Leetcode 1278
  JAVA/minchanges.java
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#117 Vertical Traversal of Binary Tree.cpp
  C++/Vertical Traversal of Binary Tree.cpp
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#127 Create SearchSubString.py
  PYTHON/SearchSubString.py
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#132 Create BubbleSort.cpp
  C++/SelectionSort.cpp
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#135 Added JAVA code for Topological Sort
  JAVA/Dijkstra.java
  JAVA/Topological_Sort.java
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#138 added median-maximization
  C++/medianMaximization.cpp
  C++/simpleStrangeSort.cpp
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#139 Create project2.php
  php/project2.php
Labels: response-needed, changes-required

#140 Added a java program
  JAVA/LinkedList/CheckLLPalindrome
Labels: changes-required

#141 Create BinarySearch.java
  JAVA/Sorted Array to Binary Search Tree.java
Labels: hacktoberfest2021

#143 Create InputDisplay and PrimeNumberAdder in Kotlin
  Kotlin/InputDisplay.kt
  Kotlin/PrimeNumberAdder.kt
Labels: hacktoberfest2021, response-needed, changes-required

#121 Create login.php
  php/login.php
Labels: hacktoberfest2021, Hacktoberfest, Hacktoberfest-accepted

#145 added shell sort code
  C++/ShellSort.cpp
Labels: hacktoberfest2021, Hacktoberfest, response-needed, changes-required
